- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: enable and start nginx
  ansible.builtin.systemd_service:
    enabled: yes
    state: started
    name: nginx

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: include common role    ← dash here
  include_role:
    name: common
    task_from: main
